### ISSUE TITLE
Compilation error: "only enumeration types have underlying types"

### ISSUE THREAD

**Issue by trombonehero** [jwtowner/lug#4] opened 2018-08-31 14:23 UTC
When compiling with recent libc++ (8220dac5 from 29 Aug 2018) and Clang (v8.0.0 from tip-of-tree):

```
clang version 8.0.0 (https://git.llvm.org/git/clang a12d0b0e0159b8f533297b291c79489a6322de3e) (https://git.llvm.org/git/llvm da01ae3cf249da908e28e3681845b859b2193ce8)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Users/jon/Dev/LLVM/build/bin
```

one of the compilation errors I see comes from lug's use of `std::underlying_type_t`:

```
In file included from samples/basic.cpp:8:
In file included from ./lug/lug.hpp:8:
In file included from ./lug/error.hpp:8:
In file included from /Users/jon/Dev/LLVM/build/include/c++/v1/stdexcept:46:
In file included from /Users/jon/Dev/LLVM/build/include/c++/v1/exception:81:
In file included from /Users/jon/Dev/LLVM/build/include/c++/v1/cstddef:110:
/Users/jon/Dev/LLVM/build/include/c++/v1/type_traits:4659:13: error: only
      enumeration types have underlying types
    typedef _LIBCPP_UNDERLYING_TYPE(_Tp) type;
            ^
/Users/jon/Dev/LLVM/build/include/c++/v1/__config:463:36: note: expanded from
      macro '_LIBCPP_UNDERLYING_TYPE'
#define _LIBCPP_UNDERLYING_TYPE(T) __underlying_type(T)
                                   ^
/Users/jon/Dev/LLVM/build/include/c++/v1/type_traits:4663:22: note: in
      instantiation of template class 'std::__1::underlying_type<lug::rule>'
      requested here
template <class _Tp> using underlying_type_t = typename underlying_type<...
                     ^
./lug/detail.hpp:55:41: note: in instantiation of template type alias
      'underlying_type_t' requested here
        return static_cast<T>(static_cast<std::underlying_type_t<T>>(x) ...
                                               ^
./lug/lug.hpp:1392:30: note: in instantiation of function template
      specialization 'lug::bitfield_ops::operator|<lug::rule, void>' requested
      here
        grammar grmr = start((+(Dot | Bracket | Sequence) | Empty) > eoi);
```

**Comment by jwtowner** [comment] 2024-06-08 18:46
This appears to be working in Clang & libc++ 12.0 and onward. Going to close this issue for now. I intend on migrating to C++23, which will require newer versions of the compiler anyway and I will be replacing the uses of SFINAE that was the cause of this issue with concepts and requires clauses, which should put a rest to the problem.

**Closed by jwtowner** 2024-06-08 18:46 UTC
